// Generated by CoffeeScript 1.7.1
(function() {
  var FindIP, findIP, http, iconv, parse, window;

  http = require('http');

  iconv = require('iconv-lite');

  window = (function() {
    function window() {}

    window.parse = function(ct) {
      return ct;
    };

    return window;

  })();

  parse = window.parse;

  FindIP = (function() {
    var API_URL;

    function FindIP() {}

    API_URL = "http://whois.pconline.com.cn/ipJson.jsp";

    FindIP.prototype.find = function(ip, callback) {
      var ret;
      ret = '';
      return http.get("" + API_URL + "?ip=" + ip + "&callback=parse", function(res) {
        res.setEncoding('binary');
        res.on('data', function(chunk) {
          return ret += chunk;
        });
        return res.on('end', function() {
          var buf;
          buf = new Buffer(ret, 'binary');
          ret = iconv.decode(ret, 'GBK');
          return callback(null, eval(ret));
        });
      }).on('error', function(e) {
        return callback(e);
      });
    };

    return FindIP;

  })();

  findIP = new FindIP;

  module.exports = findIP;

}).call(this);
